name: GitHub Actions practice
on: [push]
jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0-alpha.5
      - name: Install pytest
        run: pip install pytest
      - name: Run Tests
        run: python -B -m pytest
        working-directory: ./src
